version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./symfony:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - postgres
      - redis
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
