version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./symfony:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

# Exemplo de serviço adicional (descomente se quiser usar futuramente)
#  redis:
#    image: redis:alpine
#    networks:
#      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
